// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BookKeeping.Models.DB
{
    public partial class BookkeepingContext : DbContext
    {
        public BookkeepingContext()
        {
        }

        public BookkeepingContext(DbContextOptions<BookkeepingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<StatementAccounts> StatementAccounts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Categorys> Categorys { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<StatementAccounts>(entity =>
            {
                entity.HasKey(e => e.Uid);

                entity.Property(e => e.Uid).ValueGeneratedNever();

                entity.Property(e => e.Category).HasMaxLength(50);

                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.PayType).HasMaxLength(10);

                entity.Property(e => e.SubCategory).HasMaxLength(50);
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsFixedLength();

                entity.Property(e => e.CreateDay)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}